### ISSUE TITLE
Performance evaluation and Resnet18

### ISSUE THREAD

**Issue by deepseek** [xuannianz/DifferentiableBinarization#1]
@xuannianz thank you for you hard work

- How does this implementation perform compared to the official one?
- Can Resnet-18 be trained here?

**Comment by xuannianz** [comment]
Hi @deepseek ,
1. To be honest, I haven't figured out the process to measure performance.
2. No, pretrained resnet18 weights of keras is not available, you need to convert pytorch weights to keras firstly.

**Comment by deepseek** [comment]
Thanks
