### ISSUE TITLE
训练loss问题

### ISSUE THREAD

**Issue by lsr12345** [xuannianz/DifferentiableBinarization#3]
在ICDAR-2019上训练，loss一直上升的问题。

label_text格式如下：
161,0,605,0,605,195,161,195,傲椒
432,153,609,157,609,196,432,192,BOBOYU
661,93,992,105,992,200,661,188,啵啵鱼
1,191,724,212,724,271,1,253,这是一条有脾气的鱼！

**Comment by xuannianz** [comment]
learning rate 调小点试试
