### ISSUE TITLE
Download pretrain model

### ISSUE THREAD

**Issue by saiful79** [xuannianz/DifferentiableBinarization#4]
Hi,
i want to download your model from Baidu but i can not download it.  Is there an alternate way in which I could get access to the models?

Thanks!

**Comment by duforetn** [comment]
Hello, any chance you can share the pretrain model on google drive?

Thanks!

**Comment by xuannianz** [comment]
Hi, @saiful79 @duforetn 
Here it is https://drive.google.com/open?id=1ausCBrADzlhqoo6viuWP_e_zYdiqUKA7

**Comment by saiful79** [comment]
@xuannianz thanks.

**Comment by saiful9379** [comment]
thanks for sharing pretrain model
Best Regards,
Md. Saiful Islam
Studying at
Dept. of Computer Science & Engineering
Begum Rokeya University, Rangpur
Research Assistant at Semantics Lab <http://semanticslab.net/>
