### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by white-wolf-tech** [xuannianz/DifferentiableBinarization#8]
这里总会报错 
   print(xmin_valid,xmax_valid,ymin_valid,ymax_valid)
    print(xmin,xmax,ymin,ymax)
    canvas[ymin_valid:ymax_valid + 1, xmin_valid:xmax_valid + 1] = np.fmax(
        1 - distance_map[
            ymin_valid - ymin:ymax_valid - ymin,
            xmin_valid - xmin:xmax_valid - xmin],
        canvas[ymin_valid:ymax_valid + 1, xmin_valid:xmax_valid + 1])
print之后发现xmin = xmin_valid，xmax_valid = xmax，ymin_valid= ymin，ymax_valid= ymax。训练数据用的是icdar2015～

**Comment by white-wolf-tech** [comment]
是数据本身有问题？？还是预处理数据的代码有问题？

**Comment by xuannianz** [comment]
报什么错啊？

**Comment by white-wolf-tech** [comment]
好多个数据都会出现如下类似的错误
generator.py", line 96, in draw_thresh_map
    canvas[ymin_valid:ymax_valid + 1, xmin_valid:xmax_valid + 1])
ValueError: operands could not be broadcast together with shapes (35,131) (36,132)

**Comment by xuannianz** [comment]
好像是，缺了个 `+1`， 应该是 `distance_map[
            ymin_valid - ymin:ymax_valid - ymin + 1,
            xmin_valid - xmin:xmax_valid - xmin + 1]`

**Comment by white-wolf-tech** [comment]
灰常感谢🙏～
